spring.application.name=wallet_dashboard
server.port=${PORT:8080}

# MySQL Database Configuration
spring.datasource.url=jdbc:mysql://yamanote.proxy.rlwy.net:44988/railway?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=qyUZuCUrUPBGoLvHbvPNgSMAtVOvKujB
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Logging
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE